= LIBBV(3)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD

== NAME
libbv - BRL-CAD view graphics interface subroutines

== SYNOPSIS

[source,c]
----
voidpl_3box, FILE *fp, intx0, inty0, intz0, intx1, inty1, intz1);
voidpl_3cont, FILE *fp, intx, inty, intz);
voidpl_3line, FILE *fp, intx0, inty0, intz0, intx1, inty1, intz1);
voidpl_3move, FILE *fp, intx, inty, intz);
voidpl_3point, FILE *fp, intx, inty, intz);
voidpl_3space, FILE *fp, intx0, inty0, intz0, intx1, inty1, intz1);
voidpl_arc, FILE *fp, intxc, intyc, intx0, inty0, intx1, inty1);
voidpl_box, FILE *fp, intx0, inty0, intx1, inty1);
pl_circle, FILE *fp, intx, inty, intr);
voidpl_color, FILE *fp, intr, intg, intb);
voidpl_cont, FILE *fp, intx, inty);
voidpl_erase, FILE *fp);
voidpl_label, FILE *fp, const char *s);
voidpl_line, FILE *fp, intx0, inty0, intx1, inty1);
voidpl_linmod, FILE *fp, const char *s);
voidpl_move, FILE *fp, intx, inty);
voidpl_point, FILE *fp, intx, inty);
voidpl_space, FILE *fp, intx0, inty0, intx1, inty1);

----


== DESCRIPTION

These subroutines generate graphic output commands for processing with the _plot(1)_ plotting filters. They are slightly more general than those in _libplot_ as these take a file pointer. They also include the BRL 3-D extensions to the plot intermediate code.

_Pl_space_ or _pl_3space_ must be used before any of the graphic primitives to declare the amount of space necessary. See _plot3(5)_.

_Pl_box_ or _pl_3box_ draws a box between the two given opposite points. The ''pen'' will be left at the second point.

_Pl_circle_ draws a circle of radius _r_ with center at the point (_x_, `y`). Note that _circle_ and _arc_ cannot be transformed in three space if one is using a filter to do that.

_Pl_arc_ draws an arc of a circle with center at the point (_x_, `y`) between the points (_x0_, _y0_) and (_x1_, `y1`).

String arguments to _pl_label_ and _pl_linmod_ are terminated by nulls and do not contain new-lines.

There are also 2-D and 3_D double-precision versions, with arguments identical to their counterparts above. The naming conventions are to change the prefix to "pd"; examples are thus _pd_point_ and _pd_3point._ Vector versions for 3_D (also double-precision) are prefixed "pdv", as in _pdv_3point._

See _plot3(5)_ and _plot(5)_ for a description of the effect of the remaining functions.


== FILES

/usr/brlcad/lib/libbv`.`a produces output for *plot*(1G) filters


== WARNINGS

In order to compile a program containing these functions in _file.c_ it is necessary to use ``cc _file.c_ -lplot3''.

_Color_ specification and three-dimensional primitives are BRL extensions to the "unix plot" language that are not generally found on other systems.


== SEE ALSO

*plot*(1), *pl-fb*(1), *plot3*(5), *plot*(5)


== AUTHOR

BRL-CAD Team


== COPYRIGHT

This software is Copyright (c) 1989-2025 by the United States Government as represented by U.S. Army Research Laboratory.


== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to <devs@brlcad.org>


