#!/usr/bin/env bash
# mged_compare.sh — Compare "updated" vs "vanilla" MGED editing screenshots
#
# Usage: ./mged_compare.sh [updated_mged] [vanilla_mged] [out_dir]
#
# Runs mged_edit_test.sh for both builds, then uses ImageMagick to produce
# side-by-side comparison images and an HTML gallery.
#
# Prerequisites: ImageMagick (convert, montage), mged_edit_test.sh in same dir.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

UPD_MGED="${1:-${SCRIPT_DIR}/brlcad_build/bin/mged}"
VAN_MGED="${2:-${SCRIPT_DIR}/brlcad_vanilla_build/bin/mged}"
OUT_DIR="${3:-${SCRIPT_DIR}/mged_screenshots/sys}"

UPD_DIR="${OUT_DIR}/upd"
VAN_DIR="${OUT_DIR}/van"
CMP_DIR="${OUT_DIR}/compare"
mkdir -p "$UPD_DIR" "$VAN_DIR" "$CMP_DIR"

# ─── Generate screenshots for both builds ─────────────────────────────────────
echo "=== Generating UPDATED MGED screenshots ==="
"${SCRIPT_DIR}/mged_edit_test.sh" "$UPD_MGED" "$UPD_DIR" "upd"

echo ""
echo "=== Generating VANILLA MGED screenshots ==="
"${SCRIPT_DIR}/mged_edit_test.sh" "$VAN_MGED" "$VAN_DIR" "van"

# ─── Create side-by-side comparisons ──────────────────────────────────────────
echo ""
echo "=== Creating comparison images ==="

declare -A STATUS

for upd_img in "${UPD_DIR}"/upd_*_during.png "${UPD_DIR}"/upd_*_after.png; do
    [ -f "$upd_img" ] || continue
    base=$(basename "$upd_img")
    # e.g. upd_sph1_sscale_during.png → van_sph1_sscale_during.png
    van_img="${VAN_DIR}/van_${base#upd_}"

    cmp_img="${CMP_DIR}/compare_${base#upd_}"

    if [ -f "$van_img" ]; then
        # side-by-side: vanilla on left, updated on right
        if command -v montage &>/dev/null; then
            montage -geometry +0+0 -tile 2x1 \
                -label "VANILLA" "$van_img" \
                -label "UPDATED" "$upd_img" \
                "$cmp_img" 2>/dev/null || \
            convert +append "$van_img" "$upd_img" "$cmp_img" 2>/dev/null || \
            cp "$upd_img" "$cmp_img"
        else
            convert +append "$van_img" "$upd_img" "$cmp_img" 2>/dev/null || \
            cp "$upd_img" "$cmp_img"
        fi

        # pixel-diff check (requires ImageMagick)
        if diff_out=$(convert "$van_img" "$upd_img" -metric AE -compare -format "%[distortion]" info: 2>&1); then
            if [ "$diff_out" = "0" ] || [ "$diff_out" = "0.0" ]; then
                STATUS["$base"]="MATCH"
            else
                STATUS["$base"]="DIFF ($diff_out pixels)"
            fi
        else
            STATUS["$base"]="DIFF"
        fi
    else
        STATUS["$base"]="VAN_MISSING"
        cp "$upd_img" "$cmp_img"
    fi
done

# ─── Generate HTML gallery ─────────────────────────────────────────────────────
GALLERY="${OUT_DIR}/gallery.html"
cat > "$GALLERY" <<HTMLEOF
<!DOCTYPE html>
<html>
<head>
<title>MGED Systematic Edit Screenshot Comparison</title>
<style>
body { font-family: monospace; background: #1a1a2e; color: #e0e0e0; margin: 20px; }
h1 { color: #4fc3f7; }
h2 { color: #81c784; margin-top: 30px; border-bottom: 1px solid #444; padding-bottom: 5px; }
h3 { color: #ffb74d; }
.pair { display: flex; gap: 8px; margin: 10px 0; align-items: flex-start; flex-wrap: wrap; }
.pair figure { margin: 0; }
.pair figure figcaption { font-size: 0.8em; color: #9e9e9e; }
.pair img { border: 1px solid #444; max-width: 256px; }
.compare { margin: 10px 0; }
.compare img { border: 1px solid #4fc3f7; max-width: 100%; }
.label { font-size: 0.85em; color: #9e9e9e; margin-bottom: 4px; }
.match  { color: #66bb6a; font-weight: bold; }
.diff   { color: #ef5350; font-weight: bold; }
.miss   { color: #ffb74d; }
</style>
</head>
<body>
<h1>MGED Primitive Editing: Systematic Comparison (ae 35 25 view)</h1>
<p>Generated by <code>mged_compare.sh</code>.  Each test shows:<br>
&nbsp;&nbsp;• <strong>during-edit</strong> — faceplate GUI, illuminated wireframe, parameter labels<br>
&nbsp;&nbsp;• <strong>after-edit</strong> — geometry after parameter change</p>
<p>Left column = VANILLA MGED &nbsp;|&nbsp; Right column = UPDATED MGED</p>
<hr>
HTMLEOF

# Group images by primitive
declare -A PRIMS_SEEN
for cmp_img in "${CMP_DIR}"/compare_*_during.png "${CMP_DIR}"/compare_*_after.png; do
    [ -f "$cmp_img" ] || continue
    base=$(basename "$cmp_img" .png)           # compare_sph1_sscale_during
    base="${base#compare_}"                     # sph1_sscale_during
    prim=$(echo "$base" | cut -d_ -f1)         # sph1
    if [ -z "${PRIMS_SEEN[$prim]+x}" ]; then
        PRIMS_SEEN[$prim]=1
        echo "<h2>${prim}</h2>" >> "$GALLERY"
    fi
    op_phase="${base#${prim}_}"                # sscale_during
    op="${op_phase%_*}"                        # sscale
    phase="${op_phase##*_}"                    # during or after

    upd_img="${UPD_DIR}/upd_${base}.png"
    van_img="${VAN_DIR}/van_${base}.png"

    stat="${STATUS[${base#compare_}.png]:-unknown}"
    if [[ "$stat" == MATCH ]]; then badge='<span class="match">✓ MATCH</span>'
    elif [[ "$stat" == DIFF* ]]; then badge="<span class=\"diff\">✗ ${stat}</span>"
    else badge="<span class=\"miss\">${stat}</span>"
    fi

    cat >> "$GALLERY" <<PARTEOF
<h3>${op} — ${phase} ${badge}</h3>
<div class='pair'>
  <figure><figcaption>VANILLA</figcaption><img src='van/van_${base}.png' onerror="this.style.display='none'"></figure>
  <figure><figcaption>UPDATED</figcaption><img src='upd/upd_${base}.png' onerror="this.style.display='none'"></figure>
  <figure><figcaption>SIDE-BY-SIDE</figcaption><img src='compare/compare_${base}.png' onerror="this.style.display='none'"></figure>
</div>
PARTEOF
done

cat >> "$GALLERY" <<HTMLEOF
</body>
</html>
HTMLEOF

echo ""
echo "=== Results ==="
match_count=0; diff_count=0; miss_count=0
for key in "${!STATUS[@]}"; do
    case "${STATUS[$key]}" in
        MATCH) ((match_count++)) ;;
        DIFF*) ((diff_count++)) ;;
        *)     ((miss_count++)) ;;
    esac
done
echo "  MATCH:   $match_count"
echo "  DIFF:    $diff_count"
echo "  MISSING: $miss_count"
echo ""
echo "Gallery: $GALLERY"
echo "Done."
