# CMake generated Testfile for 
# Source directory: /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/regress/fbserv
# Build directory: /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_notls/regress/fbserv
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[regress-fbserv-stress-quick]=] "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_notls/regress/fbserv/fbserv_stress" "--workers" "8")
set_tests_properties([=[regress-fbserv-stress-quick]=] PROPERTIES  LABELS "STAND_ALONE" TIMEOUT "300" _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/regress/fbserv/CMakeLists.txt;21;brlcad_add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/regress/fbserv/CMakeLists.txt;0;")
add_test([=[regress-fbserv-stress-heavy]=] "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_notls/regress/fbserv/fbserv_stress" "--workers" "32")
set_tests_properties([=[regress-fbserv-stress-heavy]=] PROPERTIES  LABELS "STAND_ALONE" TIMEOUT "300" _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/regress/fbserv/CMakeLists.txt;29;brlcad_add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/regress/fbserv/CMakeLists.txt;0;")
