#ifndef GEOGRAM_BASIC_VERSION
#define GEOGRAM_BASIC_VERSION

#define VORPALINE_VERSION_MAJOR "1"
#define VORPALINE_VERSION_MINOR "9"
#define VORPALINE_VERSION_PATCH "7"
#define VORPALINE_VERSION "1.9.7-rc"
#define VORPALINE_BUILD_NUMBER ""
#define VORPALINE_BUILD_DATE ""
#define VORPALINE_SVN_REVISION ""

#endif
