/*
 * This file was automatically generated, do not edit.
 */

#include <geogram/bibliography/bibliography.h>

void register_embedded_bib_file(void);

void register_embedded_bib_file() {
     GEO::Biblio::register_references(
        " \n"
        "@misc{WEB:GEOGRAM, \n"
        "  title = {Geogram: a programming library of geometric algorithms}, \n"
        "  author = {Inria, project ALICE-GRAPHYS}, \n"
        "  howpublished = {\\url{http://alice.loria.fr/software/geogram/doc/html/index.html}} \n"
        "} \n"
        " \n"
        " \n"
        "@article{DBLP:journals/tog/EdelsbrunnerM90, \n"
        "  author    = {Herbert Edelsbrunner and \n"
        "               Ernst P. M{\\\"{u}}cke}, \n"
        "  title     = {Simulation of simplicity: a technique to cope with degenerate cases \n"
        "               in geometric algorithms}, \n"
        "  journal   = {{ACM} Trans. Graph.}, \n"
        "  volume    = {9}, \n"
        "  number    = {1}, \n"
        "  pages     = {66--104}, \n"
        "  year      = {1990}, \n"
        "  url       = {http://doi.acm.org/10.1145/77635.77639}, \n"
        "  doi       = {10.1145/77635.77639}, \n"
        "  timestamp = {Tue, 25 Nov 2003 07:57:25 +0100}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/journals/tog/EdelsbrunnerM90}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@inproceedings{DBLP:conf/compgeom/Shewchuk96, \n"
        "  author    = {Jonathan Richard Shewchuk}, \n"
        "  title     = {Robust Adaptive Floating-Point Geometric Predicates}, \n"
        "  booktitle = {Proceedings of the Twelfth Annual Symposium on Computational Geometry, \n"
        "               Philadelphia, PA, USA, May 24-26, 1996}, \n"
        "  pages     = {141--150}, \n"
        "  year      = {1996}, \n"
        "  url       = {http://doi.acm.org/10.1145/237218.237337}, \n"
        "  doi       = {10.1145/237218.237337}, \n"
        "  timestamp = {Fri, 12 Jun 2015 15:27:08 +0200}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/conf/compgeom/Shewchuk96}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@inproceedings{meyer:inria-00344297, \n"
        "  TITLE = {{FPG: A code generator for fast and certified geometric predicates}}, \n"
        "  AUTHOR = {Meyer, Andreas and Pion, Sylvain}, \n"
        "  URL = {https://hal.inria.fr/inria-00344297}, \n"
        "  BOOKTITLE = {{Real Numbers and Computers}}, \n"
        "  ADDRESS = {Santiago de Compostela, Spain}, \n"
        "  PAGES = {47-60}, \n"
        "  YEAR = {2008}, \n"
        "  MONTH = Jun, \n"
        "  PDF = {https://hal.inria.fr/inria-00344297/file/FPG_RNC8.pdf}, \n"
        "  HAL_ID = {inria-00344297}, \n"
        "  HAL_VERSION = {v1}, \n"
        "} \n"
        " \n"
        " \n"
        " \n"
        " \n"
        " \n"
        " \n"
        " \n"
        " \n"
        " \n"
        " \n"
        " \n"
        " \n"
        " \n"
        " \n"
        " \n"
        " \n"
        " \n"
        " \n"
        " \n"
        " \n"
        " \n"
        " \n"
        " \n"
        " \n"
        " \n"
        "@article{DBLP:journals/paapp/BuatoisCL09, \n"
        "  author    = {Luc Buatois and \n"
        "               Guillaume Caumon and \n"
        "               Bruno L{\\'{e}}vy}, \n"
        "  title     = {Concurrent number cruncher: a {GPU} implementation of a general sparse \n"
        "               linear solver}, \n"
        "  journal   = {{IJPEDS}}, \n"
        "  volume    = {24}, \n"
        "  number    = {3}, \n"
        "  pages     = {205--223}, \n"
        "  year      = {2009}, \n"
        "  url       = {http://dx.doi.org/10.1080/17445760802337010}, \n"
        "  doi       = {10.1080/17445760802337010}, \n"
        "  timestamp = {Tue, 09 Nov 2010 08:30:19 +0100}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/journals/paapp/BuatoisCL09}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        " \n"
        "@article{DBLP:journals/tog/LiuWLSYLY09, \n"
        "  author    = {Yang Liu and \n"
        "               Wenping Wang and \n"
        "               Bruno L{\\'{e}}vy and \n"
        "               Feng Sun and \n"
        "               Dong{-}Ming Yan and \n"
        "               Lin Lu and \n"
        "               Chenglei Yang}, \n"
        "  title     = {On centroidal voronoi tessellation - energy smoothness and fast computation}, \n"
        "  journal   = {{ACM} Trans. Graph.}, \n"
        "  volume    = {28}, \n"
        "  number    = {4}, \n"
        "  pages     = {101:1--101:17}, \n"
        "  year      = {2009}, \n"
        "  url       = {http://doi.acm.org/10.1145/1559755.1559758}, \n"
        "  doi       = {10.1145/1559755.1559758}, \n"
        "  timestamp = {Wed, 04 Jan 2017 11:50:25 +0100}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/journals/tog/LiuWLSYLY09}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@article{DBLP:journals/cgf/YanLLSW09, \n"
        "  author    = {Dong{-}Ming Yan and \n"
        "               Bruno L{\\'{e}}vy and \n"
        "               Yang Liu and \n"
        "               Feng Sun and \n"
        "               Wenping Wang}, \n"
        "  title     = {Isotropic Remeshing with Fast and Exact Computation of Restricted \n"
        "               Voronoi Diagram}, \n"
        "  journal   = {Comput. Graph. Forum}, \n"
        "  volume    = {28}, \n"
        "  number    = {5}, \n"
        "  pages     = {1445--1454}, \n"
        "  year      = {2009}, \n"
        "  url       = {http://dx.doi.org/10.1111/j.1467-8659.2009.01521.x}, \n"
        "  doi       = {10.1111/j.1467-8659.2009.01521.x}, \n"
        "  timestamp = {Tue, 09 Sep 2014 19:02:15 +0200}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/journals/cgf/YanLLSW09}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@inproceedings{DBLP:conf/imr/LevyB12, \n"
        "  author    = {Bruno L{\\'{e}}vy and \n"
        "               Nicolas Bonneel}, \n"
        "  title     = {Variational Anisotropic Surface Meshing with Voronoi Parallel Linear \n"
        "               Enumeration}, \n"
        "  booktitle = {Proceedings of the 21st International Meshing Roundtable, {IMR} 2012, \n"
        "               October 7-10, 2012, San Jose, CA, {USA}}, \n"
        "  pages     = {349--366}, \n"
        "  year      = {2012}, \n"
        "  url       = {http://dx.doi.org/10.1007/978-3-642-33573-0_21}, \n"
        "  doi       = {10.1007/978-3-642-33573-0_21}, \n"
        "  timestamp = {Tue, 16 Jun 2015 19:31:31 +0200}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/conf/imr/LevyB12}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        " \n"
        " \n"
        " \n"
        " \n"
        " \n"
        "@inproceedings{DBLP:conf/gmp/YanWLL10, \n"
        "  author    = {Dong{-}Ming Yan and \n"
        "               Wenping Wang and \n"
        "               Bruno L{\\'{e}}vy and \n"
        "               Yang Liu}, \n"
        "  title     = {Efficient Computation of 3D Clipped Voronoi Diagram}, \n"
        "  booktitle = {Advances in Geometric Modeling and Processing, 6th International Conference, \n"
        "               {GMP} 2010, Castro Urdiales, Spain, June 16-18, 2010. Proceedings}, \n"
        "  pages     = {269--282}, \n"
        "  year      = {2010}, \n"
        "  url       = {http://dx.doi.org/10.1007/978-3-642-13411-1_18}, \n"
        "  doi       = {10.1007/978-3-642-13411-1_18}, \n"
        "  timestamp = {Tue, 09 Sep 2014 19:02:15 +0200}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/conf/gmp/YanWLL10}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@article{DBLP:journals/cad/YanWLL13, \n"
        "  author    = {Dong{-}Ming Yan and \n"
        "               Wenping Wang and \n"
        "               Bruno L{\\'{e}}vy and \n"
        "               Yang Liu}, \n"
        "  title     = {Efficient computation of clipped Voronoi diagram for mesh generation}, \n"
        "  journal   = {Computer-Aided Design}, \n"
        "  volume    = {45}, \n"
        "  number    = {4}, \n"
        "  pages     = {843--852}, \n"
        "  year      = {2013}, \n"
        "  url       = {http://dx.doi.org/10.1016/j.cad.2011.09.004}, \n"
        "  doi       = {10.1016/j.cad.2011.09.004}, \n"
        "  timestamp = {Tue, 09 Sep 2014 19:02:15 +0200}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/journals/cad/YanWLL13}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        "@article{DBLP:journals/cad/Levy16, \n"
        "  author    = {Bruno L{\\'{e}}vy}, \n"
        "  title     = {Robustness and efficiency of geometric programs: The Predicate Construction \n"
        "               Kit {(PCK)}}, \n"
        "  journal   = {Computer-Aided Design}, \n"
        "  volume    = {72}, \n"
        "  pages     = {3--12}, \n"
        "  year      = {2016}, \n"
        "  url       = {http://dx.doi.org/10.1016/j.cad.2015.10.004}, \n"
        "  doi       = {10.1016/j.cad.2015.10.004}, \n"
        "  timestamp = {Tue, 16 Feb 2016 16:08:12 +0100}, \n"
        "  biburl    = {http://dblp.uni-trier.de/rec/bib/journals/cad/Levy16}, \n"
        "  bibsource = {dblp computer science bibliography, http://dblp.org} \n"
        "} \n"
        " \n"
        " \n"
        " \n"
        "@ARTICLE{Lloyd82leastsquares, \n"
        "    author = {Stuart P. Lloyd}, \n"
        "    title = {Least squares quantization in pcm}, \n"
        "    journal = {IEEE Transactions on Information Theory}, \n"
        "    year = {1982}, \n"
        "    volume = {28}, \n"
        "    pages = {129--137} \n"
        "} \n"
        " \n"
        "@article{Du:1999:CVT:340312.340319, \n"
        " author = {Du, Qiang and Faber, Vance and Gunzburger, Max}, \n"
        " title = {Centroidal Voronoi Tessellations: Applications and Algorithms}, \n"
        " journal = {SIAM Rev.}, \n"
        " issue_date = {Dec. 1999}, \n"
        " volume = {41}, \n"
        " number = {4}, \n"
        " month = dec, \n"
        " year = {1999}, \n"
        " issn = {0036-1445}, \n"
        " pages = {637--676}, \n"
        " numpages = {40}, \n"
        " url = {http://dx.doi.org/10.1137/S0036144599352836}, \n"
        " doi = {10.1137/S0036144599352836}, \n"
        " acmid = {340319}, \n"
        " publisher = {Society for Industrial and Applied Mathematics}, \n"
        " address = {Philadelphia, PA, USA}, \n"
        " keywords = {Voronoi tessellations, centroids, clustering, data compression, vector quantization}, \n"
        "} \n"
        " \n"
        " \n"
        " \n"
        " \n"
        " \n"
        " \n"
     );

}
