# CMake generated Testfile for 
# Source directory: /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/libged/tests
# Build directory: /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/src/libged/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[ged_test_tops_moss]=] "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/src/libged/tests/ged_test_tops" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/libged/tests/ged_tests.g")
set_tests_properties([=[ged_test_tops_moss]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/libged/tests/CMakeLists.txt;5;brlcad_add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/libged/tests/CMakeLists.txt;0;")
add_test([=[ged_test_list]=] "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/src/libged/tests/ged_test_list" "2")
set_tests_properties([=[ged_test_list]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/libged/tests/CMakeLists.txt;11;brlcad_add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/libged/tests/CMakeLists.txt;0;")
add_test([=[ged_test_material]=] "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/src/libged/tests/ged_test_material" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/src/libged/tests/ged_test_material.g")
set_tests_properties([=[ged_test_material]=] PROPERTIES  ENVIRONMENT "BRLCAD_ROOT=/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov" _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/libged/tests/CMakeLists.txt;27;brlcad_add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/libged/tests/CMakeLists.txt;0;")
add_test([=[ged_test_search]=] "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/src/libged/tests/ged_test_search" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/libged/tests/search_tests.g")
set_tests_properties([=[ged_test_search]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/libged/tests/CMakeLists.txt;42;brlcad_add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/libged/tests/CMakeLists.txt;0;")
add_test([=[rt_search_tests]=] "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/src/libged/tests/rt_search_test" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/libged/tests/rt_search_tests.g")
set_tests_properties([=[rt_search_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/libged/tests/CMakeLists.txt;48;brlcad_add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/libged/tests/CMakeLists.txt;0;")
add_test([=[ged_test_prim_cmds_exist]=] "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/src/libged/tests/ged_check_prim_cmds")
set_tests_properties([=[ged_test_prim_cmds_exist]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/libged/tests/CMakeLists.txt;54;brlcad_add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/libged/tests/CMakeLists.txt;0;")
subdirs("bot")
subdirs("draw")
