= DEBUGBU(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
debugbu - Allows the user to set or check the debug flags used by libbu.

== SYNOPSIS

[source]
----
debugbu [<hex_code>]
----


== DESCRIPTION

Allows the user to set or check the debug flags used by _libbu_. With no arguments, the *debugbu* command displays all the possible settings for the _bu_debug_ flag and the current value. When a _hex_code_ is supplied, that value is used as the new value for _bu_debug_. Similar debug commands for other _BRL-CAD_ libraries are *debuglib* for _librt_ and *debugnmg* for the NMG portion of _librt_.


== EXAMPLES

The first example shows the use of the *debugbu* command (without an argument) to display all possible settings for the _bu_debug_ flag and the current value. The second example shows the use of the *debugbu* command with a hex code, which is used as the new value for _bu_debug_.

.Display a list of available bu_debug values and the current value.
[example]
====
mged>*debugbu*

Lists available _bu_debug_ values and the current value.

====

.Set a new value for bu_debug.
[example]
====
mged>*debugbu 2*

Sets _bu_debug_ to <MEM_CHECK>.

====


== AUTHOR

BRL-CAD Team


== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to <devs@brlcad.org>


