= EDIT TRANSLATE(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
edit translate - Translates the position of one or more objects.

== SYNOPSIS

[source]
----
edit [options] geometry translate [-a|-r] [-x|-y|-z] [-k FROM] TO
----

== DESCRIPTION

The *translate* subcommand of the *edit* command moves an object to a new
position.  It is documented fully under the *edit* manual page.

See *edit*(nged) for the complete description of the geometry specifier
syntax, global options (*-S*, *-f*, *-F*, *-i*), and all translate options
and examples.

== EXAMPLES

.Translate sph.s to absolute position (15, 0, 0)
[example]
====
mged> **edit sph.s translate -a 15 0 0**
====

.Move sph.s by a relative delta of (5, 0, 0)
[example]
====
mged> **edit sph.s translate -r 5 0 0**
====

.Move sph.s from its center to other.s's center
[example]
====
mged> **edit sph.s translate -k sph.s -a other.s**
====

.Align several objects to the same z-elevation
[example]
====
mged> **edit obj1 translate -k . -a -z obj2**
====

== SEE ALSO

*edit*(nged)

[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org

