= WMATER(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD MGED Commands

== NAME
wmater - Lists the shader name and parameters, RGB color, RGB_valid flag, and the inheritance flag to the specified file for the listed objects.

== SYNOPSIS

[source]
----
wmater {<file>} {<objects>}
----


[[description]]
== DESCRIPTION

Lists the shader name and parameters, RGB color, _RGB_valid_ flag, and the inheritance flag to the specified _file_ for the listed_objects_. The format used is compatible with the *rmater* command. If _file_ already exists, the new data is appended to it.


[[examples]]
== EXAMPLES

The example shows the use of the *wmater* command to list the shader parameters of two objects to a specified file.

.List the shader parameters of two objects to a specified file.
[example]
====
mged>*wmater mater_file group1 regiona*

Lists the shader parameters of _group1_ and _regiona_ to _mater_file_.

====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to <devs@brlcad.org>
