# CMake generated Testfile for 
# Source directory: /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/regress/rtwizard
# Build directory: /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/regress/rtwizard
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[regress-rtwiz_m35_A]=] "/usr/local/bin/cmake" "-DEXEC=/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/bin/rtwizard" "-P" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/regress/rtwizard/regress-rtwiz_m35_A.cmake")
set_tests_properties([=[regress-rtwiz_m35_A]=] PROPERTIES  LABELS "STAND_ALONE" TIMEOUT "300" _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Targets.cmake;897;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/regress/rtwizard/CMakeLists.txt;36;brlcad_regression_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/regress/rtwizard/CMakeLists.txt;0;")
add_test([=[regress-rtwiz_m35_B]=] "/usr/local/bin/cmake" "-DEXEC=/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/bin/rtwizard" "-P" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/regress/rtwizard/regress-rtwiz_m35_B.cmake")
set_tests_properties([=[regress-rtwiz_m35_B]=] PROPERTIES  DEPENDS "regress-rtwiz_m35_A" LABELS "STAND_ALONE" TIMEOUT "300" _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Targets.cmake;897;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/regress/rtwizard/CMakeLists.txt;44;brlcad_regression_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/regress/rtwizard/CMakeLists.txt;0;")
add_test([=[regress-rtwiz_m35_C]=] "/usr/local/bin/cmake" "-DEXEC=/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/bin/rtwizard" "-P" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/regress/rtwizard/regress-rtwiz_m35_C.cmake")
set_tests_properties([=[regress-rtwiz_m35_C]=] PROPERTIES  DEPENDS "regress-rtwiz_m35_B" LABELS "STAND_ALONE" TIMEOUT "300" _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Targets.cmake;897;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/regress/rtwizard/CMakeLists.txt;56;brlcad_regression_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/regress/rtwizard/CMakeLists.txt;0;")
add_test([=[regress-rtwiz_m35_D]=] "/usr/local/bin/cmake" "-DEXEC=/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/bin/rtwizard" "-P" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/regress/rtwizard/regress-rtwiz_m35_D.cmake")
set_tests_properties([=[regress-rtwiz_m35_D]=] PROPERTIES  DEPENDS "regress-rtwiz_m35_C" LABELS "STAND_ALONE" TIMEOUT "300" _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Targets.cmake;897;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/regress/rtwizard/CMakeLists.txt;68;brlcad_regression_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/regress/rtwizard/CMakeLists.txt;0;")
add_test([=[regress-rtwiz_m35_E]=] "/usr/local/bin/cmake" "-DEXEC=/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/bin/rtwizard" "-P" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/regress/rtwizard/regress-rtwiz_m35_E.cmake")
set_tests_properties([=[regress-rtwiz_m35_E]=] PROPERTIES  DEPENDS "regress-rtwiz_m35_D" LABELS "STAND_ALONE" TIMEOUT "300" _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Targets.cmake;897;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/regress/rtwizard/CMakeLists.txt;80;brlcad_regression_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/regress/rtwizard/CMakeLists.txt;0;")
add_test([=[regress-rtwiz_m35_F]=] "/usr/local/bin/cmake" "-DEXEC=/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/bin/rtwizard" "-P" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/regress/rtwizard/regress-rtwiz_m35_F.cmake")
set_tests_properties([=[regress-rtwiz_m35_F]=] PROPERTIES  DEPENDS "regress-rtwiz_m35_E" LABELS "STAND_ALONE" TIMEOUT "300" _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Targets.cmake;897;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/regress/rtwizard/CMakeLists.txt;92;brlcad_regression_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/regress/rtwizard/CMakeLists.txt;0;")
add_test([=[regress-rtwiz_m35_edge_only]=] "/usr/local/bin/cmake" "-DEXEC=/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/bin/rtwizard" "-P" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/regress/rtwizard/regress-rtwiz_m35_edge_only.cmake")
set_tests_properties([=[regress-rtwiz_m35_edge_only]=] PROPERTIES  DEPENDS "regress-rtwiz_m35_F" LABELS "STAND_ALONE" TIMEOUT "300" _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Targets.cmake;897;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/regress/rtwizard/CMakeLists.txt;104;brlcad_regression_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/regress/rtwizard/CMakeLists.txt;0;")
add_test([=[regress-rtwiz_m35_edge_only_color]=] "/usr/local/bin/cmake" "-DEXEC=/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/bin/rtwizard" "-P" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/regress/rtwizard/regress-rtwiz_m35_edge_only_color.cmake")
set_tests_properties([=[regress-rtwiz_m35_edge_only_color]=] PROPERTIES  DEPENDS "regress-rtwiz_m35_edge_only" LABELS "STAND_ALONE" TIMEOUT "300" _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Targets.cmake;897;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/regress/rtwizard/CMakeLists.txt;116;brlcad_regression_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/regress/rtwizard/CMakeLists.txt;0;")
