# CMake generated Testfile for 
# Source directory: /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/libged/tests/draw
# Build directory: /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/src/libged/tests/draw
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[ged_test_drawing_basic]=] "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/src/libged/tests/draw/ged_test_draw" "-c" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/libged/tests/draw")
set_tests_properties([=[ged_test_drawing_basic]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/libged/tests/draw/CMakeLists.txt;53;brlcad_add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/libged/tests/draw/CMakeLists.txt;0;")
add_test([=[ged_test_drawing_faceplate]=] "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/src/libged/tests/draw/ged_test_faceplate" "-c" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/libged/tests/draw")
set_tests_properties([=[ged_test_drawing_faceplate]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/libged/tests/draw/CMakeLists.txt;75;brlcad_add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/libged/tests/draw/CMakeLists.txt;0;")
add_test([=[ged_test_drawing_lod]=] "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/src/libged/tests/draw/ged_test_lod" "-c" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/libged/tests/draw")
set_tests_properties([=[ged_test_drawing_lod]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/libged/tests/draw/CMakeLists.txt;94;brlcad_add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/libged/tests/draw/CMakeLists.txt;0;")
add_test([=[ged_test_drawing_select]=] "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/src/libged/tests/draw/ged_test_select_draw" "-c" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/libged/tests/draw")
set_tests_properties([=[ged_test_drawing_select]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/libged/tests/draw/CMakeLists.txt;151;brlcad_add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/libged/tests/draw/CMakeLists.txt;0;")
add_test([=[ged_test_drawing_quad]=] "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/src/libged/tests/draw/ged_test_quad" "-c" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/libged/tests/draw")
set_tests_properties([=[ged_test_drawing_quad]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/libged/tests/draw/CMakeLists.txt;197;brlcad_add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/libged/tests/draw/CMakeLists.txt;0;")
