execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/pkg_mkIndex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/archer" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/archer")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/auto_mkindex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/archer" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/archer")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/auto_mkindex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/boteditor" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/boteditor")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/pkg_mkIndex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/checker" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/checker")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/auto_mkindex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/checker" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/checker")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/pkg_mkIndex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/geometree" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/geometree")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/auto_mkindex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/geometree" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/geometree")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/pkg_mkIndex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/igraph" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/igraph")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/auto_mkindex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/igraph" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/igraph")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/pkg_mkIndex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/hv3" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/hv3")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/auto_mkindex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/hv3" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/hv3")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/pkg_mkIndex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/lib" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/lib")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/auto_mkindex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/lib" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/lib")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/auto_mkindex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/lod" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/lod")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/auto_mkindex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/mged" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/mged")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/pkg_mkIndex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/plot3-dm" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/plot3-dm")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/auto_mkindex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/plot3-dm" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/plot3-dm")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/auto_mkindex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/sdialogs/scripts" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/sdialogs/scripts")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/pkg_mkIndex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/sdialogs" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/sdialogs")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/auto_mkindex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/sdialogs" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/sdialogs")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/pkg_mkIndex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/shotvis" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/shotvis")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/auto_mkindex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/shotvis" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/shotvis")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/auto_mkindex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/swidgets/scripts" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/swidgets/scripts")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/pkg_mkIndex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/swidgets" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/swidgets")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/auto_mkindex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/swidgets" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/swidgets")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/pkg_mkIndex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/tcllib" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/tcllib")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/auto_mkindex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/tcllib" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/tcllib")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/pkg_mkIndex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/util" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/util")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/auto_mkindex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/util" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/util")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/pkg_mkIndex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/auto_mkindex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/pkg_mkIndex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/rtwizard/lib" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/rtwizard/lib")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/auto_mkindex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/rtwizard/lib" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/rtwizard/lib")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/pkg_mkIndex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/rtwizard" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/rtwizard")
endif()
execute_process(COMMAND ${BTCLSH} "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/CMakeTmp/auto_mkindex.tcl" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/rtwizard" RESULT_VARIABLE BRES)
if(BRES)
  message(FATAL_ERROR "Failed to process /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_cov/share/tclscripts/rtwizard")
endif()
