# CMake generated Testfile for 
# Source directory: /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/librt/tests
# Build directory: /home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_notls/src/librt/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[rt_bundle]=] "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_notls/src/librt/tests/bundle")
set_tests_properties([=[rt_bundle]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/librt/tests/CMakeLists.txt;2;brlcad_add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/librt/tests/CMakeLists.txt;0;")
add_test([=[rt_pattern_5]=] "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_notls/src/librt/tests/rt_pattern" "5")
set_tests_properties([=[rt_pattern_5]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/librt/tests/CMakeLists.txt;7;brlcad_add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/librt/tests/CMakeLists.txt;0;")
add_test([=[rt_dvec]=] "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_notls/src/librt/tests/rt_dvec")
set_tests_properties([=[rt_dvec]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/librt/tests/CMakeLists.txt;16;brlcad_add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/librt/tests/CMakeLists.txt;0;")
add_test([=[rt_cyclic_basic]=] "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_notls/src/librt/tests/rt_cyclic" "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/librt/tests/cyclic_tests.g")
set_tests_properties([=[rt_cyclic_basic]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/librt/tests/CMakeLists.txt;60;brlcad_add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/librt/tests/CMakeLists.txt;0;")
add_test([=[rt_cache_serial_single_object]=] "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_notls/src/librt/tests/rt_cache" "1")
set_tests_properties([=[rt_cache_serial_single_object]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/librt/tests/CMakeLists.txt;63;brlcad_add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/librt/tests/CMakeLists.txt;0;")
add_test([=[rt_cache_parallel_single_object]=] "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_notls/src/librt/tests/rt_cache" "2")
set_tests_properties([=[rt_cache_parallel_single_object]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/librt/tests/CMakeLists.txt;64;brlcad_add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/librt/tests/CMakeLists.txt;0;")
add_test([=[rt_cache_serial_multiple_identical_objects]=] "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_notls/src/librt/tests/rt_cache" "3" "10")
set_tests_properties([=[rt_cache_serial_multiple_identical_objects]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/librt/tests/CMakeLists.txt;65;brlcad_add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/librt/tests/CMakeLists.txt;0;")
add_test([=[rt_cache_parallel_multiple_identical_objects]=] "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_notls/src/librt/tests/rt_cache" "4" "10")
set_tests_properties([=[rt_cache_parallel_multiple_identical_objects]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/librt/tests/CMakeLists.txt;66;brlcad_add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/librt/tests/CMakeLists.txt;0;")
add_test([=[rt_cache_serial_multiple_different_objects]=] "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_notls/src/librt/tests/rt_cache" "5" "10")
set_tests_properties([=[rt_cache_serial_multiple_different_objects]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/librt/tests/CMakeLists.txt;67;brlcad_add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/librt/tests/CMakeLists.txt;0;")
add_test([=[rt_cache_parallel_multiple_different_objects]=] "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_notls/src/librt/tests/rt_cache" "6" "10")
set_tests_properties([=[rt_cache_parallel_multiple_different_objects]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/librt/tests/CMakeLists.txt;68;brlcad_add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/librt/tests/CMakeLists.txt;0;")
add_test([=[rt_cache_parallel_multiple_different_objects_hierarchy_1]=] "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_notls/src/librt/tests/rt_cache" "7" "10")
set_tests_properties([=[rt_cache_parallel_multiple_different_objects_hierarchy_1]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/librt/tests/CMakeLists.txt;69;brlcad_add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/librt/tests/CMakeLists.txt;0;")
add_test([=[rt_search_stress]=] "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad_build_notls/src/librt/tests/rt_search_stress")
set_tests_properties([=[rt_search_stress]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;1;add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake:107:EVAL;0;;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/misc/CMake/BRLCAD_Test_Wrappers.cmake;107;cmake_language;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/librt/tests/CMakeLists.txt;83;brlcad_add_test;/home/runner/work/brlcad_quickiterate/brlcad_quickiterate/brlcad/src/librt/tests/CMakeLists.txt;0;")
subdirs("edit")
